import os from 'os';

console.log('eol:: ', os.EOL);
console.log('-------------');
console.log('arch:: ', os.arch());
console.log('-------------');
console.log('availableParallelism:: ', os.availableParallelism());
console.log('-------------');
console.log('constants:: ', os.constants);
console.log('-------------');
console.log('cpus:: ', os.cpus());
console.log('-------------');
console.log('devNull:: ', os.devNull);
console.log('-------------');
console.log('endianness:: ', os.endianness());
console.log('-------------');
console.log('freemem:: ', os.freemem());
console.log('-------------');
console.log('getPriority:: ', os.getPriority());
console.log('-------------');
console.log('homedir:: ', os.homedir());
console.log('-------------');
console.log('hostname:: ', os.hostname());
console.log('-------------');
console.log('loadavg:: ', os.loadavg());
console.log('-------------');
console.log('networkInterfaces:: ', os.networkInterfaces());
console.log('-------------');
console.log('machine:: ', os.machine());
console.log('-------------');
console.log('networkInterfaces:: ', os.networkInterfaces());
console.log('-------------');
console.log('platform:: ', os.platform());
console.log('-------------');
console.log('release:: ', os.release());
console.log('-------------');
console.log('setPriority:: ', os.setPriority);
console.log('-------------');
console.log('tmpdir:: ', os.tmpdir());
console.log('-------------');
console.log('totalmem:: ', os.totalmem());
console.log('-------------');
console.log('type:: ', os.type());
console.log('-------------');
console.log('uptime:: ', os.uptime());
console.log('-------------');
console.log('userInfo:: ', os.userInfo());
console.log('-------------');
console.log('version:: ', os.version());

